import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <header className="w-full border border-black p-5">header</header>
        {children}
        <footer className="w-full border border-black p-5">footer</footer>
      </body>
    </html>
  );
}