import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <header className="text-center py-5 border border-black">
          <h1>헤더</h1>
        </header>
        <main className="py-60">
        {children}
        </main>
        <footer className="text-center py-5 border border-black">
          <h1>푸터</h1>
        </footer>
      </body>
    </html>
  );
}
